### ISSUE TITLE
google analytics setting

### ISSUE THREAD

**Issue by Enoch-Kim** [DSC-University-of-Seoul/dsc-university-of-seoul.github.io#1]

**Comment by hojunee** [comment]
Google Analytics에서 name과 url 설정을 어떻게 해야하는지 남겨주세요.

ref)
![스크린샷 2020-09-27 오전 12 15 42](https://user-images.githubusercontent.com/32982728/94343928-b2177000-0056-11eb-91cc-3c804a127434.png)

**Comment by Enoch-Kim** [comment]
웹사이트 이름 : dsc-university-of-seoul.github.io
url : https://dsc-university-of-seoul.github.io
면 될 것 같습니다.

**Comment by hojunee** [comment]
![스크린샷 2020-09-30 오후 12 06 32](https://user-images.githubusercontent.com/32982728/94638698-85dd4700-0315-11eb-8278-e049753daccc.png)

기초 설정 완료하였고, 트래킹 코드를 발급받았습니다. 위 스크린샷을 참조해주세요.
추가적인 작업 요청이 있으시다면 지속적으로 이 issue에 comment 남겨주세요.
