### ISSUE TITLE
블로그 색상 재정비 

### ISSUE THREAD

**Issue by min6choi** [DSC-University-of-Seoul/dsc-university-of-seoul.github.io#104]
블로그 색상을 dsc 색상 가이드라인(이번학기 모집 포스터 제작할 때 사용했습니다)에 맞게 재정비 해보는건 어떨까요? 

<img width="314" alt="google color" src="https://user-images.githubusercontent.com/57276820/116404337-7f8e5980-a869-11eb-823b-6f5b982222a3.png">

**Comment by MOBUMIN** [comment]
테마를 만들어서 theme = summer 이런식으로 색상 한번에 변경하는 기능 ! 어떤가요?
