### ISSUE TITLE
역대 DSC 멤버들 탭 Alumni

### ISSUE THREAD

**Issue by MOBUMIN** [DSC-University-of-Seoul/dsc-university-of-seoul.github.io#111]
DSC에서 나가면 이름 사라지는게 아쉬워서 about 페이지에 탭을 만드는건 어떤가요?

현재 멤버들은 첫 탭에, 이전 멤버들은 합쳐서 그냥 두번째 탭에 뜨도록요!

![image](https://user-images.githubusercontent.com/57705512/116806588-1a887b80-ab69-11eb-8039-2b8a6ac2e78f.png)

**Comment by Enoch-Kim** [comment]
추가로 Alumni 기수마다 주면 더 좋을 것 같아요!

**Comment by hojunee** [comment]
기수는 서수형 데이터 말고 범주형 데이터면 좋을 것 같네옹~
