### ISSUE TITLE
사진에 캡션 달기

### ISSUE THREAD

**Issue by LeeMir** [DSC-University-of-Seoul/dsc-university-of-seoul.github.io#118]
글 작성하다가, 이게 무슨 사진인지 캡션을 달고 싶을 때 markdown에서는 따로 지원하지 않는 것 같습니다.
(그냥 밑에 글을 적으면 되지만, 캡션 티가 나게 글자 크기도 좀 줄이고 색상도 연하게 하면 더 좋을 것 같네요!)

방법을 두 개정도 찾아보았는데, jekyll + markdown에서 가능한 `{: }` 에 새로운 클래스? 같은 무언가를 커스텀을 하는 방법이 있고,
css로 `img + em { }`으로 스타일링해서 이미지 밑에 \*캡션 메시지\*로 다는 기능을 추가하는 방법이 있습니다!

아래 사진은 후자 방법으로 글자크기 축소 / 회색 / 가운데 정렬 넣어서 제가 임의로 해보았고,
전자 방법은 정확히 무슨 방법인지 몰라서 조금 더 알아봐야합니당

(딱히 테스트할 방법이 생각이 안나서 로컬에서 기존 게시물에서 테스트해보았습니다.)

![image](https://user-images.githubusercontent.com/42960217/117825116-000d7b00-b2aa-11eb-987d-bbbb0bb38166.png)

코드는 아래와 같습니다. (사진 바로 밑에 기울임을 적용해서 텍스트를 작성해야 캡션으로 기능)
```markdown
![teachable_machine_page.jpeg](../assets/images/post-Teachable-Machine/teachable_machine_page.jpeg)
*캡션 메시지 예시*
```

**Comment by MOBUMIN** [comment]
이런 기능 있으면 좋을 것 같아요!
구현하게되면 CONTRIBUTING.MD에다가 어떻게 쓰는지 적어둬야 할 것 같아요 ㅎㅎ

**Comment by min6choi** [comment]
찬성합니다! 개인적으로 margin-top 조금만 넣으면 가독성이 훨씬 좋아질 것 같네요:)

**Comment by LeeMir** [comment]
>구현하게되면 CONTRIBUTING.MD에다가 어떻게 쓰는지 적어둬야 할 것 같아요 ㅎㅎ

ㄴ넵 알겠습니다

>찬성합니다! 개인적으로 margin-top 조금만 넣으면 가독성이 훨씬 좋아질 것 같네요:)

ㄴ반영해보겠습니다! ㅎㅎ
