### ISSUE TITLE
Posts 개수 개선안

### ISSUE THREAD

**Issue by LeeMir** [DSC-University-of-Seoul/dsc-university-of-seoul.github.io#120]
Featured Posts 목록은 이전에 4개까지 표시되도록 수정했는데,

그 밑에 Posts 목록은 한 페이지에 10개까지 표시가 되네요!

3열에 10개라서 1개가 삐져나오는 게 불편해서 그런데 12개나 9개로 맞추는 게 어떨까요?

**Comment by min6choi** [comment]
저는 12개로 가는게 좋을 것 같아요!
