### ISSUE TITLE
블로그 하단 이미지 변경 

### ISSUE THREAD

**Issue by min6choi** [DSC-University-of-Seoul/dsc-university-of-seoul.github.io#126]
블로그 하단의 이미지가 단색으로 변경해보면 어떨까요? 
단색으로 변경하면 좀 더 심플하게 보일 것 같아요.

<img width="1440" alt="Screenshot 2021-05-18 at 3 52 49 PM" src="https://user-images.githubusercontent.com/57276820/118608021-368c4e00-b7f4-11eb-9d96-beadb368dc6f.png">

**Comment by LeeMir** [comment]
저 사진은 jekyll theme에 같이 딸려온 샘플 이미지인가요?

단색도 괜찮고 아예 비슷한 구도의 시립대 사진으로 바꾸는 것도 좋을 것 같아요 :)
