### ISSUE TITLE
방문자수조회(google analytics)

### ISSUE THREAD

**Issue by MOBUMIN** [DSC-University-of-Seoul/dsc-university-of-seoul.github.io#141]
DSC 계정 있는지 확인하고 연결하기

**Comment by min6choi** [comment]
DSC 계정 호준님께 전달 받았습니다. 주말내로 방문자수조회 적용하겠습니다~

**Comment by min6choi** [comment]
계정 확인결과 이미 google analytics에 팀블로그가 등록되어있는 것으로 확인 되었습니다.

**Comment by MOBUMIN** [comment]
@min6choi 

이미 google analytics로 조회가 가능한가요?

**Comment by min6choi** [comment]
> @min6choi
> 
> 이미 google analytics로 조회가 가능한가요?

google analytics에 블로그 주소를 등록해서 조회하는 방식인데 제가 공식계정으로 접속했을 때 이미 블로그가 등록되어있더라고요. 
추가적으로 할 사항이 없어서 종료했습니다.

**Comment by MOBUMIN** [comment]
혹시 계정 공유 가능할까요?

**Comment by min6choi** [comment]
> 혹시 계정 공유 가능할까요?

넵 swit으로 dm드릴께요!

**Comment by MOBUMIN** [comment]
이미 잘 측정되고 있었네요 ㅠㅠ 혼란을 드려 죄송합니다
