### ISSUE TITLE
VirtualDOM 포스트 깨짐

### ISSUE THREAD

**Issue by hojunee** [DSC-University-of-Seoul/dsc-university-of-seoul.github.io#150]
![image](https://user-images.githubusercontent.com/32982728/124601918-55799900-dea3-11eb-9016-c5e4236c27e1.png)

확인 부탁드립니다.

**Comment by LeeMir** [comment]
확인 결과 해당 부분은 주소 지정할 때 확장자를 대문자로 해서 발생한 오류였으며,

어제 작성자인 승종님께서 직접 수정해 PR을 넣어주셨는데(#146) 아직 해당 PR의 PR-Review가 되지 않아 적용이 되지 않았습니다..!

얼른 PR-Review 진행하도록 하겠습니다!

**Comment by hojunee** [comment]
빠른 확인 감사합니당~ 해결 완료되면 Close 부탁드려요.

**Comment by LeeMir** [comment]
넵 알겠습니다~!
