### ISSUE TITLE
about 페이지 프로필 깨짐

### ISSUE THREAD

**Issue by LeeMir** [DSC-University-of-Seoul/dsc-university-of-seoul.github.io#175]
![image](https://user-images.githubusercontent.com/42960217/145550317-de08eede-52fb-4f0b-b366-0d2c04a2cdd8.png)

호준님 프로필이 깨지고 있습니당

**Comment by SHEELE41** [comment]
![image](https://user-images.githubusercontent.com/24821303/145552920-b13e16e9-3a31-4369-8a2c-34798167dd35.png)
수정 완료
