### ISSUE TITLE
header 수정

### ISSUE THREAD

**Issue by Enoch-Kim** [DSC-University-of-Seoul/dsc-university-of-seoul.github.io#18]
* header logo를 animation으로 왼쪽 위로 올라가게 구현하거나 다른 방법 찾기

**Comment by jeongukjae** [comment]
이건 어떤 내용인가요??

**Comment by MOBUMIN** [comment]
full logo와 좌측 상단에 있는 logo가 조금 이상해보여서 큰 로고에 애니메이션을 줘서 작은 로고가 되도록 하는건 어떻냐는 의견이 있었습니당😀

**Comment by Enoch-Kim** [comment]
Don't need
