### ISSUE TITLE
필요 없는 파일 제거

### ISSUE THREAD

**Issue by LeeMir** [DSC-University-of-Seoul/dsc-university-of-seoul.github.io#190]
![image](https://user-images.githubusercontent.com/42960217/152534770-f0f69db3-7be5-4eda-a275-090f1ebb4279.png)

> 지도 서비스 성능 최적화 ~~~.md
> mersenne.jpg

이 두 가지는 루트 디렉토리에서 필요 없는 파일 같습니다!

**Comment by ms9648** [comment]
확인해보니 mersenne.jpg는 중복되는 파일이어서 제거했고, 지도 서비스 성능 최적화 ~~~.md 파일의 경우에는 없었습니다.

**Comment by LeeMir** [comment]
> 지도 서비스 성능 최적화 ~~~.md 파일의 경우에는 없었습니다.

해당 파일은 당사자분께 직접 말씀드려서 지웠습니다! 😄
