### ISSUE TITLE
DisQus 세팅 

### ISSUE THREAD

**Issue by MOBUMIN** [DSC-University-of-Seoul/dsc-university-of-seoul.github.io#2]
Disqus 세팅해주세요

**Comment by hojunee** [comment]
Install Disqus on my website 를 통해서 진행하고 있습니다.
두 사진을 업로드하겠습니다. 이를 참고해서 comment 남겨주세요.

1. 다음 화면에서 제가 어떤 Action을 해야하는지 알려주세요.
![스크린샷 2020-09-27 오전 12 09 37](https://user-images.githubusercontent.com/32982728/94343854-1be34a00-0056-11eb-9a0a-af5995da2463.png)

2. 다음 화면의 Field에 채울 내용을 정리해서 보내주세요.
![스크린샷 2020-09-27 오전 12 09 46](https://user-images.githubusercontent.com/32982728/94343839-f9513100-0055-11eb-9e87-3cf6d35e0c81.png)

**Comment by MOBUMIN** [comment]
혹시 아이디 비번좀 알려주실 수 있나용!? 처음 첨부하신 페이지 보면서 코드 추가 해야하는 거라!

제가 보안을 위협하는 것 같다면 이거 참고하셔도.. 돼요... ㅋㅋㅋ! >https://dev-yakuza.github.io/ko/jekyll/disqus/
