### ISSUE TITLE
about.md 작성

### ISSUE THREAD

**Issue by Enoch-Kim** [DSC-University-of-Seoul/dsc-university-of-seoul.github.io#3]

**Comment by hojunee** [comment]
about.md에는 어떤 내용이 들어갈 예정인가요? (DSC UOS에 대한 소개? DSC UOS Team 블로그에 대한 소개? 등)

**Comment by MOBUMIN** [comment]
그때 얘기했던 건 멤버들에 대한 정보를 적는 것이었던 것 같은데...(가물가물) 팀블로그에 대한 소개도 필요할 것같네요..!

**Comment by jeongukjae** [comment]
> about.md에는 어떤 내용이 들어갈 예정인가요? (DSC UOS에 대한 소개? DSC UOS Team 블로그에 대한 소개? 등)

@beeetea 말씀하신 내용과 멤버에 대한 내용은 다 필요할 것 같아요!

**Comment by min6choi** [comment]
DSC(Developer Student Club)는 Google의 지원으로 운영되는 대학생 개발자 커뮤니티로 학생들에게 유익한 영향을 미치고 역량을 강화하여 기술을 통해 공동체에 가치있는 영향을 미치고자 하는 목표를 바탕으로 진행되고 있습니다. 

 세계 각국에서 DSC가 진행되고 있으며 한국은 DSC korea라는 이름으로 작년 2019년 8월에 시작되어 현재 많은 대학교에서 운영되고 있습니다. 


DSC UOS
저희 DSC UOS는 개발에 관심이 있는 서울시립대학교 학생 26명의 멤버로 구성된 커뮤니티로 지역사회에 공헌할 수 있는 프로젝트를 만들고자 하는 공동 목표를 가지고 함께 운영하고 있습니다. 


> 예전에 올려주신 이화여대 블로그소개랑 저희 킥오프 바탕으로 DSC랑 DSC UOS소개글 작성해 봤는데 혹시 고칠 부분 있나요? 
> 그리고 이후에는 저희 정기모임 어떤식으로 운영하고 있는지랑 DSC 링크만 추가로 넣으면 될 것 같은데 어떻게 생각하세요?

**Comment by MOBUMIN** [comment]
코어 멤버들에 관한 내용도 필요할 것 같아요! 내용은 각자 작성해야겠지만 기본 틀 같은게 만들어져야 할 듯 합니다.
