### ISSUE TITLE
author.md contents 채우기

### ISSUE THREAD

**Issue by Enoch-Kim** [DSC-University-of-Seoul/dsc-university-of-seoul.github.io#7]
* 코어멤버
* 일반 멤버는 Blog에 글을 쓸 때 넣기

**Comment by jeongukjae** [comment]
#12 과 같이 해결

**Comment by MOBUMIN** [comment]
web 부분 개인 웹사이트 vs 깃헙 ?

**Comment by MOBUMIN** [comment]
현재는
subin:
  name: 수빈
이런 양식으로 작성 중인데, 포스트 작성자 이름 띄울 때 성을 붙일지 이런 양식도 지정해야할 것 같아요!

**Comment by jeongukjae** [comment]
Resolved by #25
