### ISSUE TITLE
블로그 운영진 태그 표시

### ISSUE THREAD

**Issue by MOBUMIN** [DSC-University-of-Seoul/dsc-university-of-seoul.github.io#99]
블로그 운영진 한 거 자랑해야죠!

블로그 운영진 징표를 만들어서 배치해봅시댱 :)

**Comment by LeeMir** [comment]
author.yml에 태그 추가를 말씀하시는 건가요?

**Comment by MOBUMIN** [comment]
> author.yml에 태그 추가를 말씀하시는 건가요?

about 페이지에 블로그 운영진 태그를 보이도록 하고 싶었습니다 ( 디자인은 assignee 맘대루.. )
그러려면 author.yml에 태그 추가가 되어야겠네요 ㅎㅎ

**Comment by Enoch-Kim** [comment]
이거 제발 해주세요 ㅠㅠ

**Comment by LeeMir** [comment]
ㅋㅋㅋ 혹시 미리 정해놓은 디자인이나 아이디어가 있나요???

**Comment by MOBUMIN** [comment]
ㅋㅋㅋ없어요 근데 명재님 이런 데에 관심 있을 것 같아요 그렇죠 ??

**Comment by LeeMir** [comment]
>명재님 이런 데에 관심 있을 것 같아요 그렇죠 ??

ㄴ단호하게 아니라고 말씀드릴 수 있겠습니다.

저는 그라데이션을 광적으로 좋아해서 저한테 맡기시면 큰-일나실걸요? 😅

**Comment by LeeMir** [comment]
한번 해보았습니다..

### 1번
![image](https://user-images.githubusercontent.com/42960217/118283865-c7201100-b50a-11eb-8efe-921d72004818.png)

- - -

### 2번
![image](https://user-images.githubusercontent.com/42960217/118288309-41eb2b00-b50f-11eb-8d36-97e0e449c74a.png)

**Comment by LeeMir** [comment]
이거는 재미로..ㅎㅎ

![Hnet-image (4)](https://user-images.githubusercontent.com/42960217/118292067-37cb2b80-b513-11eb-80a7-3c4dd1a51f8f.gif)

**Comment by min6choi** [comment]
> 이거는 재미로..ㅎㅎ
> 
> ![Hnet-image (4)](https://user-images.githubusercontent.com/42960217/118292067-37cb2b80-b513-11eb-80a7-3c4dd1a51f8f.gif)

이것도 좋은데 회전 속도 좀 천천히 수정하고, border px 조금 키운 것도 볼 수 있을까요?

**Comment by LeeMir** [comment]
>이것도 좋은데 회전 속도 좀 천천히 수정하고, border px 조금 키운 것도 볼 수 있을까요?

테두리에 그라데이션을 입히는 것은 `border-color`로 할 수 없어서 `background-image`로 접근을 해야했는데,
이 경우 animation을 적용해도 이어지지 않고 끊기더라구요 😥😥
그라데이션 없이 `border-color`로 단색 테두리가 부드럽게 변하는 animation을 만들어봤는데, 그건 어떤 색깔을 가져와도 봐줄 수 없어 차마 찍을 수 없었습니다.

그래서 회전 속도 줄이고 px를 키우면 아래와 같이 됩니다 😅

![Hnet-image (5)](https://user-images.githubusercontent.com/42960217/118365814-37956380-b5d9-11eb-980b-c3a43acaa802.gif)

**Comment by min6choi** [comment]
> > 이것도 좋은데 회전 속도 좀 천천히 수정하고, border px 조금 키운 것도 볼 수 있을까요?
> 
> 테두리에 그라데이션을 입히는 것은 `border-color`로 할 수 없어서 `background-image`로 접근을 해야했는데,
> 이 경우 animation을 적용해도 이어지지 않고 끊기더라구요 😥😥
> 그라데이션 없이 `border-color`로 단색 테두리가 부드럽게 변하는 animation을 만들어봤는데, 그건 어떤 색깔을 가져와도 봐줄 수 없어 차마 찍을 수 없었습니다.
> 
> 그래서 회전 속도 줄이고 px를 키우면 아래와 같이 됩니다 😅
> 
> ![Hnet-image (5)](https://user-images.githubusercontent.com/42960217/118365814-37956380-b5d9-11eb-980b-c3a43acaa802.gif)

아... border px는 적당한데 animation이 끊겨서 제가 원하던 모습이 아니네요 ㅠㅠ 
혹시 가이드라인 색상 중 #fbbc05 #4285f4 이 두개 각각 적용한 뒤 올려주실 수 있나요? 제 생각엔 애니메이션 때문이라도 단색으로 가는게 좀 더 나을 것 같아요!

**Comment by LeeMir** [comment]
>혹시 가이드라인 색상 중 #fbbc05 #4285f4 이 두개 각각 적용한 뒤 올려주실 수 있나요? 제 생각엔 애니메이션 때문이라도 단색으로 가는게 좀 더 나을 것 같아요!

단색은 이렇게 생겼습니다...

![Hnet-image (6)](https://user-images.githubusercontent.com/42960217/118385016-3cdcc780-b646-11eb-9c3a-d341454d9248.gif)

**Comment by LeeMir** [comment]
원하는 방향은 아닌데 그라데이션이랑 애니메이션이랑 같이 쓸 수 있네요..!
끊기는 건 제가 편집점을 잘못잡아서 그런거라 원래는 부드럽게 연결됩니다..!

![Hnet-image (9)](https://user-images.githubusercontent.com/42960217/118385549-b971a500-b64a-11eb-89f3-dee05039e7aa.gif)

**Comment by MOBUMIN** [comment]
혹시 저거 border랑 같이 왕관 대신에 네모난 칸으로 BlogTeam 있으면 이상할까요? ㅎㅎ
완전 멋있긴한데 저것만 하면 무슨 표시인지 모를 것 같아서요!
왕관방식
![image](https://user-images.githubusercontent.com/57705512/118389810-ae2c7280-b666-11eb-94af-1427101a6a82.png)
태그방식
![image](https://user-images.githubusercontent.com/57705512/118389817-b5538080-b666-11eb-954b-f89d8e8a8a20.png)

**Comment by Enoch-Kim** [comment]
명재님.. 개쩌네요..
